# Generated by Django 3.2.3 on 2021-07-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/profile_default.jpg', upload_to='profile_pics'),
        ),
    ]
