# Generated by Django 3.2.3 on 2021-07-10 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210709_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='title',
        ),
    ]
