# Generated by Django 3.2.3 on 2021-07-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_productvariant_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
        migrations.AlterField(
            model_name='order',
            name='address2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
