# Generated by Django 3.2.3 on 2021-06-08 03:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_order_order_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Product',
            new_name='OrderProduct',
        ),
    ]
