# Generated by Django 3.2.3 on 2021-06-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210615_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
