# Generated by Django 3.2.3 on 2021-06-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_variant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='ProductImage',
        ),
        migrations.RenameModel(
            old_name='Variant',
            new_name='ProductVariant',
        ),
    ]
