# Generated by Django 3.2.3 on 2021-06-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_productvariant_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name_plural': 'Product images'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color')], default='size', max_length=50),
        ),
    ]
